function generateData() {
    let flatIdCounter = 1;

    
    const data = [
        {
            id: 1,
            images: ['/images/Primorskiy1.jpg', '/images/Primorskiy2.jpg', '/images/Primorskiy3.jpg', '/images/Primorskiy4.jpg',],
            nameComplex: 'Приморский',
            relinquishment: 'IV кв 2027',
            price: 75000,
            adress: 'пр. Петра I 45Б',
            img2: '/images/Plan1Primorskiy.jpeg',
            map: '3Af7a9e58994e07c4260eed3a826069f5e1a3dc5972843cf80223779c0ae47442a', 
            dataFlat: [
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '1/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '1/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '1/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '1/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '1/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '1/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '1/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '1/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '1/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '1/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '2/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '2/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '2/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '2/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '2/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '2/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '1/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '2/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '2/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '2/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '2/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '3/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '3/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '3/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '3/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '3/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '3/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '3/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '3/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '3/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '3/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '3/16', },
                
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '4/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '4/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '4/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '4/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '4/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '4/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '4/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '4/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '4/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '4/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '5/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '5/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '5/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '5/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '5/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '5/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '5/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '5/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '5/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '5/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '6/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '6/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '6/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '6/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '6/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '6/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '6/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '6/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '6/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '6/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '7/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '7/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '7/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '7/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '7/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '7/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '7/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '7/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '7/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '7/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '8/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '8/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '8/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '8/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '8/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '8/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '8/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '8/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '8/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '8/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '9/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '9/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '9/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '9/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '9/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '9/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '9/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '9/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '9/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '9/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '10/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '10/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '10/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '10/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '10/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '10/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '10/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '10/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '10/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '10/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '11/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '11/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '11/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '11/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '11/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '11/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '11/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '11/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '11/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '11/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '12/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '12/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '12/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '12/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '12/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '12/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '12/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '12/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '12/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '12/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '13/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '13/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '13/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '13/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '13/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '13/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '13/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '13/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '13/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '13/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '14/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '14/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '14/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '14/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '14/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '14/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '14/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '14/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '14/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '14/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '15/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '15/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '15/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '15/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '15/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '15/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '15/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '15/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '15/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '15/16', },

                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12.jpeg', area: 45.12, rooms: 1, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy45,12^2.jpeg', area: 45.12, rooms: 1, floor: '16/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy55,07.jpeg', area: 55.07, rooms: 1, floor: '16/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy62,88.jpeg', area: 62.88, rooms: 2, floor: '16/16', },
                { id: flatIdCounter++, img: '/images/Plan1Primorskiy86,65.jpeg', area: 86.65, rooms: 2, floor: '16/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy22,35.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 22.35, rooms: 2, floor: '16/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy33,4.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 33.4, rooms: 2, floor: '16/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '16/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy45,12^2.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 45.12, rooms: 2, floor: '16/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy67,85.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 67.85, rooms: 2, floor: '16/16', },
                { id: flatIdCounter++, img: '/images/Plan2Primorskiy77,21.jpeg', img2: '/images/Plan2Primorskiy.jpeg', area: 77.21, rooms: 2, floor: '16/16', },

            ]
        },
        {
            id: 2,
            images: ['/images/Primakova1.jpeg', '/images/Primakova2.jpeg', '/images/Primakova3.jpeg', '/images/Primakova4.jpeg', '/images/PrimakovaPlan1.jpeg', '/images/PrimakovaPlan2.jpeg',],
            nameComplex: 'Примакова',
            relinquishment: 'IV кв 2027',
            price: 75000,
            img2: '/images/PrimakovaPlan1.jpeg',
            adress: 'пр. Петра I 45Б',
            map: '3Af7a9e58994e07c4260eed3a826069f5e1a3dc5972843cf80223779c0ae47442a',
            dataFlat: [
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '1/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '1/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '2/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '2/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '3/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '3/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '4/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '4/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '5/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '5/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '6/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '6/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '7/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '7/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '8/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '8/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '9/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '9/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '10/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '10/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '11/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '11/12',},

                { id: flatIdCounter++, img: '/images/PrimakovaPlan30.jpeg', area: 30, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan30,7.jpeg', area: 30.7, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan34.jpeg', area: 34, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan35.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 35, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan42,3.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 42.3, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan51,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 51.5, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58.jpeg', area: 58, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5.jpeg', area: 58.5, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan58,5-2.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 58.5, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan62,8.jpeg', area: 62.8, rooms: 1, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan79.jpeg', area: 79, rooms: 2, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan89,7.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 89.7, rooms: 2, floor: '12/12',},
                { id: flatIdCounter++, img: '/images/PrimakovaPlan111,5.jpeg', img2: '/images/PrimakovaPlan2.jpeg', area: 111.5, rooms: 3, floor: '12/12',},
            ]
    
        },
        {
            id: 3,
            images: ['/images/Perspectiva1.jpg', '/images/Perspectiva2.jpg', '/images/Perspectiva3.jpg', '/images/Perspectiva4.jpg', '/images/PlanPerspectiva.jpeg'],
            nameComplex: 'Перспектива',
            relinquishment: '4кв 2026',
            price: 70000,
            adress: 'пр. Петра I 45Б',
            img2: '/images/PlanPerspectiva.jpeg',
            map: '3Af7a9e58994e07c4260eed3a826069f5e1a3dc5972843cf80223779c0ae47442a',
            dataFlat: [
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '1/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '1/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '1/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '1/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '1/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '2/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '2/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '2/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '2/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '2/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '3/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '3/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '3/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '3/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '3/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '4/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '4/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '4/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '4/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '4/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '5/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '5/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '5/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '5/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '5/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '6/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '6/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '6/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '6/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '6/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '7/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '7/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '7/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '7/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '7/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '8/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '8/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '8/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '8/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '8/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '9/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '9/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '9/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '9/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '9/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '10/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '10/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '10/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '10/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '10/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '11/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '11/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '11/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '11/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '11/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '12/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '12/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '12/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '12/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '12/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '13/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '13/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '13/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '13/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '13/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '14/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '14/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '14/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '14/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '14/15',},

                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62.jpeg', area: 37.62, rooms: 1, floor: '15/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva37,62-2.jpeg', area: 37.62, rooms: 1, floor: '15/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59.jpeg', area: 49.59, rooms: 1, floor: '15/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva49,59-2.jpeg', area: 49.59, rooms: 1, floor: '15/15',},
                { id: flatIdCounter++, img: '/images/PlanPerspectiva72,73.jpeg', area: 72.73, rooms: 2, floor: '15/15',},
            ]
        },
        {
            id: 4,
            images: ['/images/Semeiniy1.jpg', '/images/Semeiniy2.jpg', '/images/Semeiniy3.jpg', '/images/Semeiniy4.jpg', '/images/Plan1Semeiniy.jpg', '/images/Plan2Semeiniy.jpg' ],
            nameComplex: 'Семейный',
            relinquishment: '4кв 2028',
            price: 70000,
            adress: 'пр. Петра I 45Б',
            img2: '/images/Plan1Semeiniy.jpg',
            map: '3Af7a9e58994e07c4260eed3a826069f5e1a3dc5972843cf80223779c0ae47442a',
            dataFlat: [
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '1/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '1/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '2/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '2/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '3/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '3/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '4/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '4/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '5/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '5/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '6/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '6/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '7/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '7/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '8/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '8/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '9/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '9/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '10/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '10/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '11/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '11/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '12/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '12/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '13/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '13/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '14/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '14/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '15/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '15/16',},

                { id: flatIdCounter++, img: '/images/Plan1Semeiniy32.jpg', area: 32, rooms: 1, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy34.jpg', area: 34, rooms: 1, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy43.jpg', area: 43, rooms: 1, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy46.jpg', area: 46, rooms: 1, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy48.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 48, rooms: 1, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy49.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 49, rooms: 1, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy52.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 52, rooms: 1, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy63.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 63, rooms: 2, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy64.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 64, rooms: 2, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy67.jpg', area: 67, rooms: 2, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan1Semeiniy68.jpg', area: 68, rooms: 2, floor: '16/16',},
                { id: flatIdCounter++, img: '/images/Plan2Semeiniy82.jpg', img2: '/images/Plan2Semeiniy.jpg', area: 82, rooms: 3, floor: '16/16',},
            ]
        },
    ]
    
    return data;
}

export default generateData();